spring.application.name=auth-service

server.servlet.context-path=/api
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtSecret=mySecretKey123456789shbfhbvfshvbsfhvskhbfhusdbvihsbibsadihv
spring.app.jwtExpirationMs=30000000

user.service.url=${USER_SERVICE}
company.service.url=${COMPANY_SERVICE}

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.jpa.open-in-view=false

logging.level.com.breakingjob.authservice=DEBUG