version: '3.9'

services:

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - breakingjob-network

  company-service:
    build:
      context: ./company-service-ms
    container_name: company-service
    ports:
      - "8082:8080"
    restart: unless-stopped
    networks:
      - breakingjob-network

  user-service:
    build:
      context: ./user-service-ms
    container_name: user-service
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - breakingjob-network

  job-service:
    build:
      context: ./job-service-ms
    container_name: job-service
    ports:
      - "8083:8080"
    restart: unless-stopped
    networks:
      - breakingjob-network

  edda-ai:
    build:
      context: ./EddaAI
    container_name: edda-ai
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - breakingjob-network

  pgbouncer:
    build:
      context: ./infrastructure/pgbouncer
    container_name: pgbouncer
    ports:
      - "6432:6432"
    restart: unless-stopped
    networks:
      - breakingjob-network

networks:
  breakingjob-network:
    driver: bridge
